// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://erxxyzvsmjkyubdxqcfd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVyeHh5enZzbWpreXViZHhxY2ZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ3OTA4MjEsImV4cCI6MjA4MDM2NjgyMX0.wyvHRVeqjF9vmLGfMIIPJ61qnFA-7blB8S7OVNapITE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});